// Typed native player-input controls for WoW 3.3.5a build 12340.
#pragma once

#include "game/Binding.hpp"
#include "offsets/engine/Input.hpp"

namespace wxl::game::input
{
    namespace off = wxl::offsets::engine::input;
    using Control = off::Control;

    inline void* Instance() { return *reinterpret_cast<void**>(off::kControl); }

    /// The timestamp generated by the client's own input/update clock.
    inline uint32_t ActionTime() { return *reinterpret_cast<const uint32_t*>(off::kActionTime); }

    inline bool Begin(Control control, uint32_t timeMs)
    {
        void* const input = Instance();
        return input && Native<off::BeginFn>(off::kBegin)(input, uint32_t(control), timeMs) != 0;
    }

    inline bool End(Control control, uint32_t timeMs)
    {
        void* const input = Instance();
        return input && Native<off::EndFn>(off::kEnd)(input, uint32_t(control), timeMs, 0) != 0;
    }

    inline void Commit(uint32_t timeMs)
    {
        if (void* const input = Instance()) Native<off::CommitFn>(off::kCommit)(input, timeMs, 1);
    }
}
